name: Java CI Pipeline

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java environment
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    # Step 3: Build and test the application
    - name: Run tests
      run: |
        javac -cp .:junit-platform-console-standalone.jar LoginApp.java LoginAppTest.java
        java -jar junit-platform-console-standalone.jar --class-path . --scan-class-path
